#!/usr/bin/env php
<?php

include 'tools/Cocos/core.php';

$runner = new Cocos\Commands\Runner();

Cocos\Exceptions\ExceptionHandle::handle(function() use ($runner){
	$runner->runCommands($_SERVER['argv']);
});

/**
 *Command List 
 *  ge js
 *      generate project.json
 *  ge res
 *      generate src/resource.js
 *  ge create:command commaneName action0 action1...
 *      create tools/Cocos/Commands/CommandCommandName.php
 *  ge create:layer layername layerStoreDir 
 *		--rewrite 
 * 		--first
 *      create src/Layers/LayerNameLayer.js
 *	ge first firstScene
 *
 *
 * 
 */