#!/usr/bin/env php
<?php

include 'tools/Cocos/core.php';

$runner = new Cocos\Commands\Runner();

try{
	$runner->runCommands($_SERVER['argv'],__DIR__);
}catch(\Cocos\Exceptions\CocosException $e){
	echo $e->getMessage().PHP_EOL;
}
exit;