#!/usr/bin/env php
<?php

include 'tools/Cocos/core.php';

$runner = new Cocos\Commands\Runner();

Cocos\Exceptions\ExceptionHandle::handle(function() use ($runner){
	$runner->runCommands($_SERVER['argv']);
});

