        
var res = {
	DemoPlayer_Cowboy0_plist : "res/DemoPlayer/Cowboy0.plist",
	DemoPlayer_Cowboy0_png : "res/DemoPlayer/Cowboy0.png",
	DemoPlayer_DemoPlayer_ExportJson : "res/DemoPlayer/DemoPlayer.ExportJson",
	Font_bm_0_png : "res/Font/bm_0.png",
	Font_font_fnt : "res/Font/font.fnt",
	Font_font_0_png : "res/Font/font_0.png",
	Font_font_1_png : "res/Font/font_1.png",
	HD_CloseNormal_png : "res/HD/CloseNormal.png",
	HD_CloseSelected_png : "res/HD/CloseSelected.png",
	HD_HelloWorld_jpg : "res/HD/HelloWorld.jpg",
	HelloWorld_png : "res/HelloWorld.png",
	HungryHero_fonts_font_fnt : "res/HungryHero/fonts/font.fnt",
	HungryHero_fonts_font_png : "res/HungryHero/fonts/font.png",
	HungryHero_graphics_bgLayer_jpg : "res/HungryHero/graphics/bgLayer.jpg",
	HungryHero_graphics_bgWelcome_jpg : "res/HungryHero/graphics/bgWelcome.jpg",
	HungryHero_graphics_texture_plist : "res/HungryHero/graphics/texture.plist",
	HungryHero_graphics_texture_png : "res/HungryHero/graphics/texture.png",
	HungryHero_particles_coffee_plist : "res/HungryHero/particles/coffee.plist",
	HungryHero_particles_eat_plist : "res/HungryHero/particles/eat.plist",
	HungryHero_particles_mushroom_plist : "res/HungryHero/particles/mushroom.plist",
	HungryHero_particles_texture_png : "res/HungryHero/particles/texture.png",
	HungryHero_particles_wind_plist : "res/HungryHero/particles/wind.plist",
	HungryHero_particles_wind_png : "res/HungryHero/particles/wind.png",
	HungryHero_sounds_bgGame_mp3 : "res/HungryHero/sounds/bgGame.mp3",
	HungryHero_sounds_bgWelcome_mp3 : "res/HungryHero/sounds/bgWelcome.mp3",
	HungryHero_sounds_coffee_mp3 : "res/HungryHero/sounds/coffee.mp3",
	HungryHero_sounds_eat_mp3 : "res/HungryHero/sounds/eat.mp3",
	HungryHero_sounds_hit_mp3 : "res/HungryHero/sounds/hit.mp3",
	HungryHero_sounds_hurt_mp3 : "res/HungryHero/sounds/hurt.mp3",
	HungryHero_sounds_lose_mp3 : "res/HungryHero/sounds/lose.mp3",
	HungryHero_sounds_mushroom_mp3 : "res/HungryHero/sounds/mushroom.mp3",
	Normal_CloseNormal_png : "res/Normal/CloseNormal.png",
	Normal_CloseSelected_png : "res/Normal/CloseSelected.png",
	Normal_HelloWorld_jpg : "res/Normal/HelloWorld.jpg",
	Particle_fire_png : "res/Particle/fire.png",
	Particle_firework_png : "res/Particle/firework.png",
	Particle_particle_plist : "res/Particle/particle.plist",
	Particle_s_plist : "res/Particle/s.plist",
	Particle_s_png : "res/Particle/s.png",
	Particle_snow_png : "res/Particle/snow.png",
	Particle_star_png : "res/Particle/star.png",
	Particle_texture_png : "res/Particle/texture.png",
	bgLayer_jpg : "res/bgLayer.jpg",
	bgLayer2_png : "res/bgLayer2.png",
	bgLayer3_png : "res/bgLayer3.png",
	bgLayer4_png : "res/bgLayer4.png",
	candy_1_png : "res/candy/1.png",
	candy_2_png : "res/candy/2.png",
	candy_3_png : "res/candy/3.png",
	candy_4_png : "res/candy/4.png",
	candy_5_png : "res/candy/5.png",
	candy_bg_jpg : "res/candy/bg.jpg",
	candy_candy_plist : "res/candy/candy.plist",
	candy_candy_png : "res/candy/candy.png",
	grossini_plist : "res/grossini.plist",
	grossini_png : "res/grossini.png",
	item_2_png : "res/item_2.png",
	item_3_png : "res/item_3.png",
	map_tmx : "res/map.tmx",
	map1_tmx : "res/map1.tmx",
	sounds_sound_bg_mp3 : "res/sounds/sound.bg.mp3",
	sounds_sound_click_bubble_mp3 : "res/sounds/sound.click.bubble.mp3",
	startgame_png : "res/startgame.png",
	startgame2_png : "res/startgame2.png",
	startgame3_png : "res/startgame3.png",
	tile0_png : "res/tile0.png",
	tmw_desert_spacing_png : "res/tmw_desert_spacing.png",
};
        
var g_resources = [];
for (var i in res) {
    g_resources.push(res[i]);
}